<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stock[
<!ELEMENT stock (new-car | used-car)*>
<!ELEMENT new-car (model, price)>
<!ELEMENT used-car (model,price,milage,condition?)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT milage (#PCDATA)>
<!ELEMENT condition (#PCDATA)>
]>

<stock>
  <new-car>
    <model>Audi A3</model>
    <price>19.545€</price>
  </new-car>
  <used-car>
    <model>Ford Focus</model>
    <price>13.500€</price>
    <milage>56.000Km</milage>
    <condition>Semi-nuevo</condition>
  </used-car>
</stock>
